[package]
name = "AdventOfCode2022"
version = "0.1.0"
edition = "2021"

[lib]
name = "AdventOfCode2022Lib"
path = "src/lib.rs"

[[bin]]
name = "AdventOfCode2022Bin"
path = "src/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
